# Generated by Django 5.1.1 on 2024-11-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(help_text='autor', max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(help_text='titulo', max_length=100),
        ),
    ]
