# Generated by Django 5.1.3 on 2024-12-02 15:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_autor_alter_livro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='livros/static/img/livros'), upload_to=''),
        ),
    ]
